### ISSUE TITLE
Enhancement: Achievements

### ISSUE THREAD

**Issue by megalives717** [CodenameCrew/CodenameEngine#499]
add achievements pls

**Comment by NeeEoo** [comment]
Can be softcoded, and we wont add it natively because its kinda useless

**Comment by megalives717** [comment]
WILL ACHIEVEMENTS BE ADDED OR NO?

**Comment by NyxieFemboy** [comment]
> WILL ACHIEVEMENTS BE ADDED OR NO?

No

**Comment by NeeEoo** [comment]
How old are you?? I literally said it wont be added

**Comment by PetscopF** [comment]
> add achievements pls

They can be softcoded, since HScript allows you to access FlxG and the save data it contains.

**Comment by ItsLJcool** [comment]
Adding to this commit because I feel like an explanation needs to be here

You can code your own Achivements, CNE prob wont add native Achivement support since then all mods would need to support it as well, if not then it will break mods + its not that hard to handle your own Achivements.

It will give you full control over everything, instead of having to follow a specific ruleset that CNE defines.

Example: YoshiCrafterEngine supported Achivements, it didn't have to be supported but you were limited by what you could do.

Here is an Idea you can probably do tho:
Make your own Achivements through code and make it just a folder people can put in their own mods, kind of like an "addon" but then the modders can just reference data in their scripts and what not.

I would like to see this but not to be rude to anywone here but it would take a while before I see a good version that is user friendly pop up.
